wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1674570170.902796
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 20
data_path:
  desc: null
  value: /home/robotics20/Documents/rotem/data
dropout_1:
  desc: null
  value: 0.027793683687556105
dropout_2:
  desc: null
  value: 0.04720404224908827
dropout_3:
  desc: null
  value: 0.039895370370821547
epoch:
  desc: null
  value: 12
hidden_size_1:
  desc: null
  value: 64
hidden_size_2:
  desc: null
  value: 128
hidden_size_3:
  desc: null
  value: 32
initialize_weights:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.01786545311029036
model_path:
  desc: null
  value: /home/robotics20/Documents/rotem/models
num_classes:
  desc: null
  value: 4
pre_train_own_model:
  desc: null
  value: false
sensors:
  desc: null
  value:
  - S1
  - S2
  - S3
  - S4
  - S5
  - S6
  - S7
  - S8
  - S9
  - S10
  - S11
train_model:
  desc: null
  value: true
weight_decay:
  desc: null
  value: 2.6855359747729944e-05
