---
# Define the argument parse



# Add arguments for the configuration options
fmg_index: ['S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10', 'S11',
       'S12', 'S13', 'S15', 'S16', 'S17', 'S18', 'S21',
       'S22', 'S23', 'S24', 'S25', 'S26', 'S27', 'S28', 'S29', 'S31']
first_positoin_label_inedx: ['M1x', 'M1y', 'M1z','M2x', 'M2y', 'M2z', 'M3x', 'M3y', 'M3z', 'M4x', 'M4y', 'M4z']
positoin_label_inedx: ['M2x', 'M2y', 'M2z', 'M3x', 'M3y', 'M3z', 'M4x', 'M4y', 'M4z']
velocity_label_inedx: ['V2x','V2y','V2z','V3x','V3y','V3z','V4x','V4y','V4z']
sesion_time_stamp: ['sesion_time_stamp']
input_size: 27
num_labels : 18
sequence_length : 20
#config.seq_length*config.input_size
seq_size : 50
#config.seq_length*config.num_labels
label_seq_size : 180
norm : 'minmax'
n_layer : 4
hidden_size : 64
lstm_hidden_size : 64
lstm_num_layers : 2
dropout : 0.0
multiplier : 10
learning_rate : 0.001
weight_decay : 0.0001 
num_epochs : 1 
batch_size : 5
window_size : 30
seq_length: 5
data_path : 'data/data'
model_path: 'models/saved_models'
test_size : 0.2
val_size : 0.2
random_state : 42 
norm_labels: True
plot_data : True



...