---
# Define the argument parse



# Add arguments for the configuration options

parser.add_argument('--input_size', type=int, default=29, help='The size of the input layer.')
parser.add_argument('--num_labels', type=int, default=12, help='The number of output labels.')
parser.add_argument('--n_layer', type=int, default=3, help='The number of hidden layers.')
parser.add_argument('--hidden_size', nargs='+', type=int, default=[64, 64, 64], help='The size of each hidden layer.')
parser.add_argument('--dropout', nargs='+', type=float, default=[0.1, 0.1, 0.1], help='The dropout rate for each hidden layer.')
# Add arguments for the hyperparameters
parser.add_argument('--learning_rate', type=float, default=0.001, help='The learning rate for the optimizer.')
parser.add_argument('--num_epochs', type=int, default=100, help='The number of epochs to train for.')
parser.add_argument('--weight_decay', type=float, default=0.0, help='The weight decay for the optimizer.')
parser.add_argument('--batch_size', type=int, default=100, help='The size of batchs  .')

#dit_path 
parser.add_argument('--data_path', type=str, default='./data', help='The path to the training data.')


# split args 
parser.add_argument('--test_size', type=float, default=0.2, help='The size of the test set.')
parser.add_argument('--val_size', type=float, default=0.2, help='The size of the validation set.')
parser.add_argument('--random_state', type=int, default=42, help='The random state for data splitting.')


...