---
# Define the argument parse



# data headers 
# sensor arangment from the left 16 is the first  
# 25,24,23,22,21,20,37,36,39,38,41,40,
#19,18,17,16,31,32,33,28,29,30,42,26,27,45,44,43

# sensor locations in the string 
sensor_location: [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

fmg_index: ['S16', 'S17', 'S18', 'S19', 'S20', 'S21', 'S22', 'S23', 'S24', 'S25', 'S26', 'S27', 'S28', 'S29', 'S30', 'S31', 'S32', 'S33', 'S36', 'S37', 'S38', 'S39', 'S40', 'S41', 'S42', 'S43', 'S44', 'S45',]
# first_position_label_index: ['M1x', 'M1y', 'M1z','M2x', 'M2y', 'M2z', 'M3x', 'M3y', 'M3z', 'M4x', 'M4y', 'M4z',]
# position_label_index: ['M2x', 'M2y', 'M2z', 'M3x', 'M3y', 'M3z', 'M4x', 'M4y', 'M4z']
velocity_label_inedx: [VCx','VCy', 'VCz','VSx', 'VSy', 'VSz', 'VEx', 'VEy', 'VEz', 'VWx', 'VWy', 'VWz']
session_time_stamp: ['session_time_stamp']
label_index: ['MCx','MCy', 'MCz','MSx', 'MSy', 'MSz', 'MEx', 'MEy', 'MEz', 'MWx', 'MWy', 'MWz',]

model: 'CNN_LSTMModel'

# data parameters 
input_size: 28
num_labels : 12
sample_speed : 100

#hypermeters 
sequence_length : 100

# TCN
num_channels: [27,27,10,10,9]

##model config 
#for fully conected layers



# for lstm
lstm_hidden_size : 10
lstm_num_layers : 1 

# for transformer 
n_head: 8
# for conv
input_dim : 1 

dropout : 0.4
learning_rate : 0.0001 # best around 0.0001
weight_decay : 0.00005 # best around 0.00005
num_epochs : 1 
batch_size : 10
window_size : 30

#paths
data_path : ./data/full_muvment_clean
model_path: ./models/saved_models
best_model: ./models/saved_models/TransformerModel_epoch_1_date_29_01.pt


test_size : 0.1
val_size : 0.3
random_state : 42
shuffle_train : False
loss_func : MSELoss

wandb_on: True
norm: 'minmax'
norm_labels: True
plot_data : False
plot_pred : False
pre_trained: False
with_velocity : False
sequence : True

...